### ISSUE TITLE
基于libgdx渲染的java runtime

### ISSUE THREAD

**Issue by 120318** [DragonBones/DragonBonesJAVA#1]
您好，我已经移植了一个使用libgdx渲染的runtime版本，希望您可以看一下，地址：https://github.com/GDoom/DragonBonesJava
由于本人经验不足，而且对龙骨动画不是很了解，希望您提供一些好的建议。谢谢！

**Comment by akdcl** [comment]
你好，非常感谢你的分享，目前龙骨运行库进行了重新的设计，我发现你基于的还是以前的一个c++版本，现在的 JS/TS, AS, CPP 的 master 分支是经过重新设计了，为了保证 API 的一致和便于维护，如果可以的话，你可以参考目前的新版本进行调整，另外以后运行库将逐渐以 JS / TS 版本为主，其他版本都会在该版本稳定后，再做移植，这样也是为了便于维护，不然多版本维护会非常的困难 :)
